[2022-06-17 09:29:07,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:28:58.145633+00:00 [queued]>
[2022-06-17 09:29:07,625] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:28:58.145633+00:00 [queued]>
[2022-06-17 09:29:07,629] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 09:29:07,639] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-17 09:29:07,647] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 09:29:07,918] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-06-17 09:28:58.145633+00:00
[2022-06-17 09:29:08,191] {standard_task_runner.py:52} INFO - Started process 4759 to run task
[2022-06-17 09:29:08,503] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'is_api_available', 'manual__2022-06-17T09:28:58.145633+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmppkaw9804', '--error-file', '/tmp/tmp8qq8xh9_']
[2022-06-17 09:29:08,508] {standard_task_runner.py:80} INFO - Job 125: Subtask is_api_available
[2022-06-17 09:29:10,083] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:28:58.145633+00:00 [running]> on host adccabfb4a32
[2022-06-17 09:29:11,100] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T09:28:58.145633+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T09:28:58.145633+00:00
[2022-06-17 09:29:11,112] {http.py:97} INFO - Poking: api/
[2022-06-17 09:29:11,169] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-17 09:29:11,189] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-17 09:29:12,017] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-17 09:29:12,128] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=is_api_available, execution_date=20220617T092858, start_date=20220617T092907, end_date=20220617T092912
[2022-06-17 09:29:12,318] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-17 09:29:13,226] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
