[2022-06-20 06:37:03,880] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 06:37:03,965] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 06:37:03,966] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:03,968] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 06:37:03,971] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:04,105] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-06-17 00:00:00+00:00
[2022-06-20 06:37:04,140] {standard_task_runner.py:52} INFO - Started process 198 to run task
[2022-06-20 06:37:04,166] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'is_api_available', 'scheduled__2022-06-17T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmptqtyj8o6', '--error-file', '/tmp/tmpxcs73iun']
[2022-06-20 06:37:04,191] {standard_task_runner.py:80} INFO - Job 168: Subtask is_api_available
[2022-06-20 06:37:04,546] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-17T00:00:00+00:00 [running]> on host ca3ce831c04f
[2022-06-20 06:37:05,713] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T00:00:00+00:00
[2022-06-20 06:37:05,720] {http.py:97} INFO - Poking: api/
[2022-06-20 06:37:05,769] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-20 06:37:05,781] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-20 06:37:06,972] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-20 06:37:07,190] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=is_api_available, execution_date=20220617T000000, start_date=20220620T063703, end_date=20220620T063707
[2022-06-20 06:37:07,324] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 06:37:07,770] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
