[2022-06-20 06:40:56,085] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.create_table manual__2022-06-20T06:40:52.621468+00:00 [queued]>
[2022-06-20 06:40:56,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.create_table manual__2022-06-20T06:40:52.621468+00:00 [queued]>
[2022-06-20 06:40:56,134] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:40:56,136] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 06:40:56,142] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:40:56,223] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-06-20 06:40:52.621468+00:00
[2022-06-20 06:40:56,235] {standard_task_runner.py:52} INFO - Started process 370 to run task
[2022-06-20 06:40:56,265] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'create_table', 'manual__2022-06-20T06:40:52.621468+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmpsnv4y7sx', '--error-file', '/tmp/tmppzxry2bs']
[2022-06-20 06:40:56,289] {standard_task_runner.py:80} INFO - Job 183: Subtask create_table
[2022-06-20 06:40:56,589] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.create_table manual__2022-06-20T06:40:52.621468+00:00 [running]> on host ca3ce831c04f
[2022-06-20 06:40:57,194] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T06:40:52.621468+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T06:40:52.621468+00:00
[2022-06-20 06:40:57,373] {base.py:68} INFO - Using connection ID 'postgre_sql' for task execution.
[2022-06-20 06:40:57,454] {dbapi.py:213} INFO - Running statement: 
        DROP TABLE IF EXISTS z1_user;
        CREATE TABLE z1_user(
            user_id SERIAL PRIMARY KEY,
            firstname VARCHAR(255),
            lastname VARCHAR(255),
            country VARCHAR(255),
            username VARCHAR(255),
            password VARCHAR(255),
            email VARCHAR(255)
        )
        , parameters: None
[2022-06-20 06:40:57,845] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=create_table, execution_date=20220620T064052, start_date=20220620T064056, end_date=20220620T064057
[2022-06-20 06:40:58,139] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 06:40:58,906] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
